import Head from 'next/head';
import {BsFillMoonStarsFill, BsFillSunFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import { useState } from 'react';
import deved from '../public/charm_dev.png';
import logo from '../public/logo.png';
import Image from 'next/image';
import { Particle } from '@/components/Particle';
import { Projects } from '@/components/Projects';
import { TypeText } from '@/components/TypeText';



export default function Home() {

  const [darkMode , setDarkMode] = useState(true);

  return (
    <div className={darkMode? 'dark' : ''}>
      <Head>
        <title>Dave Charm Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {darkMode ?<Particle className = '' darkMode={false}/> : <Particle className = '' darkMode={true}/> } */}
      <Particle darkMode={darkMode}/>
      <main className='bg-white px-10 MainBackground md:px-20 lg:px-40 dark:bg-[#121212] '>
        <section className='min-h-screen relative'>
          <nav className='py-10 mb-12 flex justify-between'>
            <div className='flex flex-row items-center'>
              <Image src={logo} width={50} height={50}/>
              <h1 className='text-xl font-roboto dark:text-white'>devcharm</h1> 
            </div>
            <ul className='flex items-center'>
              <li>
                {darkMode  ?  <BsFillSunFill className='cursor-pointer text-2xl text-white' onClick={()=>{setDarkMode(!darkMode)}}/>:<BsFillMoonStarsFill className='cursor-pointer text-2xl' onClick={()=>{setDarkMode(!darkMode)}}/>}
              </li>
              <li>
                <a href="#" className='bg-gradient-to-r from-[#87801a] to-[#b5ab14] px-4 py-2 border-none rounded-md ml-8 text-white'>
                Resume
                </a>
                </li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <div className=' text-5xl text-[#F6E71D] font-medium md:text-6xl font-arial'>
              <TypeText/>
            </div>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>Mobile App Developer | Full Stack Web Developer</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 md:text-xl max-w-[900px] mx-auto dark:text-white'>Experienced web and mobile developer skilled in creating user-friendly, efficient and effective applications. Delivering top-notch results, on-time and within budget.</p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-slate-100'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          {/* <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover'/>
          </div> */}
          <div className='h-10'></div>
        </section>
      </main>
      <Projects/>
    </div>
  )
}
